export const QUESTION_MIN_TITLE_LENGTH = 10;
export const QUESTION_MAX_TITLE_LENGTH = 60;
export const QUESTION_MAX_DESCRIPTION_LENGTH = 1000;
export const QUESTION_MAX_IMAGES = 4;
export const ITEMS_PER_PAGE = 20;
