# This is currently just an export of labels used in the project
# In the future we could also use to add more and keep in sync via actions such as:
# https://github.com/micnncim/action-label-syncer
[
  { 'name': 'Backend', 'color': 'EF592F', 'description': '' },
  { 'name': 'Code: Tidying', 'color': 'B2864C', 'description': '' },
  { 'name': 'Design', 'color': '2FF7AB', 'description': null },
  { 'name': 'Difficulty:Easy', 'color': 'FFDDB2', 'description': '' },
  { 'name': 'Difficulty:Hard', 'color': 'C198E2', 'description': '' },
  { 'name': 'Difficulty:Super-Easy', 'color': 'C2E0C6', 'description': '' },
  { 'name': 'Difficulty:medium', 'color': '629AFC', 'description': '' },
  { 'name': 'Discussions', 'color': 'CC317C', 'description': '' },
  { 'name': 'Documentation', 'color': 'E0D323', 'description': '' },
  { 'name': 'Frontend', 'color': '5319E7', 'description': '' },
  { 'name': 'Global Good 🌍', 'color': 'B3E572', 'description': '' },
  { 'name': 'Good first issue', 'color': '74B5E3', 'description': null },
  { 'name': 'Help wanted', 'color': '56D639', 'description': '' },
  { 'name': 'In progress', 'color': '440B89', 'description': '' },
  { 'name': 'Mod: DevOps 🤖', 'color': 'BFD4F2', 'description': '' },
  { 'name': 'Mod: Discussions 💬', 'color': 'BFD4F2', 'description': '' },
  { 'name': 'Mod: HowTo 📰', 'color': 'BFD4F2', 'description': '' },
  { 'name': 'Mod: Maps 🗺', 'color': 'BFD4F2', 'description': '' },
  { 'name': 'Mod: Other ⬜️', 'color': 'BFD4F2', 'description': '' },
  { 'name': 'Mod: Profiles 👱', 'color': 'BFD4F2', 'description': '' },
  { 'name': 'Mod: Research 🔬', 'color': 'BFD4F2', 'description': '' },
  { 'name': 'Mod: Security👮', 'color': 'BFD4F2', 'description': '' },
  { 'name': 'Module Overview 👀', 'color': 'CEF45D', 'description': '' },
  { 'name': 'Non-Dev', 'color': 'ADADAD', 'description': '' },
  { 'name': 'Priority: High❕', 'color': 'FFB266', 'description': '' },
  { 'name': 'Priority: Low', 'color': 'C2E0C6', 'description': '' },
  { 'name': 'Priority: Medium', 'color': 'FFFF00', 'description': '' },
  { 'name': 'Priority: Urgent❕❕❕', 'color': 'FF0000', 'description': '' },
  {
    'name': 'Review: Assigned 👉',
    'color': 'D7C0A1',
    'description': 'Waiting on review from a specific dev',
  },
  {
    'name': 'Review: Changes Requested 🗨️',
    'color': 'D7C0A1',
    'description': 'Code reviewed, pending update to changes requested',
  },
  {
    'name': 'Review allow-preview ✅',
    'color': 'FFF',
    'description': 'Has received manual check for malicious code and can be safely built for preview',
  },
]
