checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": 9.0.15

yarnPath: .yarn/releases/yarn-4.5.1.cjs
