# TODO: update to a more new version
version: "2.1"
services:

  emulator:
    build:
      context: ./
      dockerfile: ./functions/Dockerfile.emulator
    ports:
    - 4001-4008:4001-4008
    volumes:
    - ./functions:/app/functions
    - ./functions/data/emulator/:/seed

    - ./functions/logs/database-debug.log:/app/database-debug.log
    - ./functions/logs/firebase-debug.log:/app/firebase-debug.log
    - ./functions/logs/firestore-debug.log:/app/firestore-debug.log
    - ./functions/logs/pubsub-debug.log:/app/pubsub-debug.log
    - ./functions/logs/ui-debug.log:/app/ui-debug.log
