# TODO: update to a more new version
version: "2.1"
services:

  emulator:
    container_name: backend
    build:
      context: ./
      dockerfile: ./containerization/Dockerfile
    depends_on:
      simulated-webhook-receiver:
        condition: service_healthy
    ports:
    - 4001-4008:4001-4008
    volumes:
    - ./:/app

  simulated-webhook-receiver:
    container_name: simulated-webhook-receiver
    build:
      context: ./packages/simulated-webhook-receiver
      dockerfile: Dockerfile
