# TODO: update to a more new version
version: "2.1"
services:

  emulator:
    build:
      context: ./
      dockerfile: ./functions/Dockerfile.emulator
    ports:
    - 4001-4008:4001-4008
    volumes:
    - ./functions:/app/functions
    - ./functions/data/emulator/:/seed