# TODO: update to a more new version
version: "2.1"
services:

  emulator:
    container_name: backend
    build:
      context: ./
      dockerfile: ./functions/emulator/Dockerfile
    ports:
    - 4001-4008:4001-4008
    volumes:
    - ./functions:/app/functions
    - ./functions/data/emulator:/seed
    - ./functions/logs:/app/logs

  simulated-webhook-receiver:
    container_name: simulated-webhook-receiver
    build:
      context: ./packages/simulated-webhook-receiver/
      dockerfile: Dockerfile
