CREATE TABLE IF NOT EXISTS "public"."banners" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "modified_at" timestamp with time zone,
    "text" "text" NOT NULL,
    "url" "text",
    "tenant_id" "text" NOT NULL
);

ALTER TABLE "public"."banners" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."banners" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

