CREATE TABLE IF NOT EXISTS "public"."file_downloads" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile_id" bigint NOT NULL,
    "content_type" "text" NOT NULL,
    "content_id" bigint NOT NULL,
    "tenant_id" "text" NOT NULL
);

ALTER TABLE ONLY "public"."file_downloads"
    ADD CONSTRAINT "file_downloads_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."file_downloads" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."file_downloads" USING (
    ("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text"))
);
