CREATE TABLE IF NOT EXISTS "public"."email_content_reach" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone,
    "tenant_id" text,
    "name" text,
    "preferences_label" text,
    "create_content_label" text,
    "default_option" boolean not null default false
);

