CREATE TABLE IF NOT EXISTS "public"."news" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "created_by" bigint,
    "deleted" boolean,
    "modified_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "comment_count" bigint DEFAULT '0'::bigint,
    "body" "text" NOT NULL,
    "moderation" "text",
    "slug" "text" NOT NULL,
    "previous_slugs" "text"[],
    "category" bigint,
    "tags" bigint[],
    "title" "text" NOT NULL,
    "total_views" bigint,
    "tenant_id" "text" NOT NULL,
    "hero_image" "json",
    "summary" "text",
    "fts" "tsvector" GENERATED ALWAYS AS ("to_tsvector"('"english"'::"regconfig", ((("title" || ' '::"text") || "body") || ("summary" || ''::"text")))) STORED,
    "is_draft" boolean DEFAULT false NOT NULL,
    "published_at" timestamp with time zone,
    "content_reach" "public"."content_reach",
    "poll" bigint,
    "content" "jsonb",
    "content_search_text" "text",
    "content_fts" "tsvector" GENERATED ALWAYS AS ("to_tsvector"('"english"'::"regconfig", ((COALESCE("title", ''::"text") || ' '::"text") || COALESCE("content_search_text", ''::"text")) || (' '::"text" || COALESCE("summary", ''::"text")))) STORED
);

CREATE INDEX "news_content_fts_idx" ON "public"."news" USING "gin" ("content_fts");

CREATE OR REPLACE FUNCTION "public"."news_search_fields"("public"."news") RETURNS "text"
    LANGUAGE "sql"
    SET search_path = public, pg_temp
    AS $_$
  SELECT $1.title || ' ' || $1.body;
$_$;

ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_tenant_id_slug_key" UNIQUE ("tenant_id", "slug");

ALTER TABLE "public"."news"
    ADD CONSTRAINT "news_poll_unique"
        UNIQUE ("poll");

CREATE INDEX "news_category_idx" ON "public"."news" USING "btree" ("category");
CREATE INDEX "news_created_by_idx" ON "public"."news" USING "btree" ("created_by");
CREATE INDEX "news_deleted_moderation_category_total_views_tags_created_a_idx" ON "public"."news" USING "btree" ("deleted", "moderation", "category", "total_views", "tags", "created_at", "comment_count", "created_by");
CREATE INDEX "news_tags_idx" ON "public"."news" USING "gin" ("tags");

ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."categories"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."news" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."news" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

-- News badges relations table
CREATE TABLE IF NOT EXISTS "public"."news_badges_relations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "news_id" bigint NOT NULL,
    "profile_badge_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "tenant_id" "text" NOT NULL
);

CREATE INDEX "idx_news_badges_relations_news_id" ON "public"."news_badges_relations" USING "btree" ("news_id");
CREATE INDEX "idx_news_badges_relations_badge_id" ON "public"."news_badges_relations" USING "btree" ("profile_badge_id");
CREATE INDEX "idx_news_badges_relations_tenant_id" ON "public"."news_badges_relations" USING "btree" ("tenant_id");
CREATE INDEX "news_badges_relations_news_tenant_idx" ON "public"."news_badges_relations" USING "btree" ("news_id", "tenant_id");
CREATE INDEX IF NOT EXISTS idx_news_badges_relations_news_badge ON public.news_badges_relations (news_id, profile_badge_id);

ALTER TABLE ONLY "public"."news_badges_relations"
    ADD CONSTRAINT "news_badges_relations_profile_badge_id_fkey" FOREIGN KEY ("profile_badge_id") REFERENCES "public"."profile_badges"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."news_badges_relations"
    ADD CONSTRAINT "news_badges_relations_news_id_fkey" FOREIGN KEY ("news_id") REFERENCES "public"."news"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."news_badges_relations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."news_badges_relations" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

CREATE OR REPLACE FUNCTION public.get_news_access(
  p_user_profile_id bigint DEFAULT NULL,
  p_is_admin boolean DEFAULT false,
  p_news_id bigint DEFAULT NULL
)
RETURNS TABLE (
  news_id bigint,
  is_readable boolean,
  cta_badge_id bigint
)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  WITH RECURSIVE
  viewer AS (
    SELECT CASE WHEN bool_or(pt.is_space) THEN 'space' ELSE 'non_space' END AS kind
    FROM profiles p
    JOIN profile_types pt ON pt.id = p.profile_type
    WHERE p.id = p_user_profile_id
  ),
  held (badge_id) AS (
    SELECT pbr.profile_badge_id
    FROM profile_badges_relations pbr
    WHERE pbr.profile_id = p_user_profile_id
    UNION
    SELECT pb.grants_badge_id
    FROM held h
    JOIN profile_badges pb ON pb.id = h.badge_id
    WHERE pb.grants_badge_id IS NOT NULL
  ),
  offered (audience_id, badge_id) AS (
    SELECT pb.id, pb.id
    FROM profile_badges pb
    CROSS JOIN viewer v
    WHERE pb.available_to IN (v.kind, 'all')
    UNION
    SELECT o.audience_id, pb.grants_badge_id
    FROM offered o
    JOIN profile_badges pb ON pb.id = o.badge_id
    WHERE pb.grants_badge_id IS NOT NULL
  ),
  restricted AS (
    SELECT nbr.news_id, p_is_admin OR bool_or(h.badge_id IS NOT NULL) AS is_readable
    FROM news_badges_relations nbr
    LEFT JOIN held h ON h.badge_id = nbr.profile_badge_id
    WHERE p_news_id IS NULL OR nbr.news_id = p_news_id
    GROUP BY nbr.news_id
  ),
  cta AS (
    SELECT DISTINCT ON (nbr.news_id) nbr.news_id, o.audience_id
    FROM news_badges_relations nbr
    JOIN offered o ON o.badge_id = nbr.profile_badge_id
    JOIN profile_badges a ON a.id = o.audience_id
    WHERE p_news_id IS NULL OR nbr.news_id = p_news_id
    ORDER BY nbr.news_id, a.premium_tier NULLS LAST, a.id
  )
  SELECT
    r.news_id,
    r.is_readable,
    CASE WHEN r.is_readable THEN NULL ELSE c.audience_id END AS cta_badge_id
  FROM restricted r
  LEFT JOIN cta c ON c.news_id = r.news_id;
$$;

CREATE OR REPLACE FUNCTION public.get_news_feed_by_content(
  p_user_profile_id bigint DEFAULT NULL,  -- NULL = unauthenticated
  p_is_admin boolean DEFAULT false,
  p_search text DEFAULT NULL,
  p_sort text DEFAULT 'Newest',
  p_skip integer DEFAULT 0,
  p_limit integer DEFAULT 20,
  p_include_locked boolean DEFAULT false
)
RETURNS TABLE (
  id bigint,
  created_at timestamptz,
  created_by bigint,
  modified_at timestamptz,
  published_at timestamptz,
  is_draft boolean,
  comment_count bigint,
  content jsonb,
  content_search_text text,
  slug text,
  summary text,
  tags bigint[],
  title text,
  total_views bigint,
  hero_image json,
  content_reach "public"."content_reach",
  profile_badges json,
  is_locked boolean,
  cta_badge_id bigint,
  total_count bigint
)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  WITH viewer_access AS (
    SELECT * FROM get_news_access(p_user_profile_id, p_is_admin)
  )
  SELECT
    n.id,
    n.created_at,
    n.created_by,
    n.modified_at,
    n.published_at,
    n.is_draft,
    n.comment_count,
    CASE WHEN l.is_locked THEN NULL ELSE n.content END AS content,
    CASE WHEN l.is_locked THEN NULL ELSE n.content_search_text END AS content_search_text,
    n.slug,
    n.summary,
    n.tags,
    n.title,
    n.total_views,
    n.hero_image,
    n.content_reach,
    (
      SELECT COALESCE(
        json_agg(json_build_object('profile_badges', row_to_json(pb))),
        '[]'::json
      )
      FROM news_badges_relations nbr
      JOIN profile_badges pb ON pb.id = nbr.profile_badge_id
      WHERE nbr.news_id = n.id
    ) AS profile_badges,
    l.is_locked,
    va.cta_badge_id,
    COUNT(*) OVER () AS total_count
  FROM news n
  LEFT JOIN viewer_access va ON va.news_id = n.id
  CROSS JOIN LATERAL (SELECT COALESCE(NOT va.is_readable, false) AS is_locked) l
  WHERE
    n.is_draft = false
    AND (n.deleted IS NULL OR n.deleted = FALSE)
    AND (NOT l.is_locked OR (p_include_locked AND va.cta_badge_id IS NOT NULL))
    AND (
      p_search IS NULL
      OR (NOT l.is_locked AND n.content_fts @@ plainto_tsquery('english', p_search))
      OR (
        l.is_locked
        AND to_tsvector('english', COALESCE(n.title, '') || ' ' || COALESCE(n.summary, ''))
          @@ plainto_tsquery('english', p_search)
      )
    )
  ORDER BY
    CASE WHEN p_sort = 'Newest'       THEN n.published_at   END DESC NULLS LAST,
    CASE WHEN p_sort = 'Comments'     THEN n.comment_count  END DESC NULLS LAST,
    CASE WHEN p_sort = 'LeastComments' THEN n.comment_count END ASC  NULLS LAST,
    n.published_at DESC  -- stable tiebreaker
  LIMIT p_limit
  OFFSET p_skip;
$$;
