CREATE TABLE IF NOT EXISTS "public"."news" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "created_by" bigint,
    "deleted" boolean,
    "modified_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "comment_count" bigint DEFAULT '0'::bigint,
    "body" "text" NOT NULL,
    "moderation" "text",
    "slug" "text" NOT NULL,
    "previous_slugs" "text"[],
    "category" bigint,
    "tags" bigint[],
    "title" "text" NOT NULL,
    "total_views" bigint,
    "tenant_id" "text" NOT NULL,
    "hero_image" "json",
    "summary" "text",
    "fts" "tsvector" GENERATED ALWAYS AS ("to_tsvector"('"english"'::"regconfig", ((("title" || ' '::"text") || "body") || ("summary" || ''::"text")))) STORED,
    "is_draft" boolean DEFAULT false NOT NULL,
    "published_at" timestamp with time zone,
    "email_content_reach" bigint
);

CREATE OR REPLACE FUNCTION "public"."news_search_fields"("public"."news") RETURNS "text"
    LANGUAGE "sql"
    SET search_path = public, pg_temp
    AS $_$
  SELECT $1.title || ' ' || $1.body;
$_$;

ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_tenant_id_slug_key" UNIQUE ("tenant_id", "slug");

CREATE INDEX "news_category_idx" ON "public"."news" USING "btree" ("category");
CREATE INDEX "news_created_by_idx" ON "public"."news" USING "btree" ("created_by");
CREATE INDEX "news_deleted_moderation_category_total_views_tags_created_a_idx" ON "public"."news" USING "btree" ("deleted", "moderation", "category", "total_views", "tags", "created_at", "comment_count", "created_by");
CREATE INDEX "news_tags_idx" ON "public"."news" USING "gin" ("tags");

ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."categories"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."news" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."news" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

-- News badges relations table
CREATE TABLE IF NOT EXISTS "public"."news_badges_relations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "news_id" bigint NOT NULL,
    "profile_badge_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "tenant_id" "text" NOT NULL
);

CREATE INDEX "idx_news_badges_relations_news_id" ON "public"."news_badges_relations" USING "btree" ("news_id");
CREATE INDEX "idx_news_badges_relations_badge_id" ON "public"."news_badges_relations" USING "btree" ("profile_badge_id");
CREATE INDEX "idx_news_badges_relations_tenant_id" ON "public"."news_badges_relations" USING "btree" ("tenant_id");
CREATE INDEX "news_badges_relations_news_tenant_idx" ON "public"."news_badges_relations" USING "btree" ("news_id", "tenant_id");
CREATE INDEX IF NOT EXISTS idx_news_badges_relations_news_badge ON public.news_badges_relations (news_id, profile_badge_id);

ALTER TABLE ONLY "public"."news_badges_relations"
    ADD CONSTRAINT "news_badges_relations_profile_badge_id_fkey" FOREIGN KEY ("profile_badge_id") REFERENCES "public"."profile_badges"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."news_badges_relations"
    ADD CONSTRAINT "news_badges_relations_news_id_fkey" FOREIGN KEY ("news_id") REFERENCES "public"."news"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."news_badges_relations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."news_badges_relations" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

CREATE OR REPLACE FUNCTION public.get_news_feed(
  p_user_profile_id bigint DEFAULT NULL,  -- NULL = unauthenticated
  p_is_admin boolean DEFAULT false,
  p_search text DEFAULT NULL,
  p_sort text DEFAULT 'Newest',
  p_skip integer DEFAULT 0,
  p_limit integer DEFAULT 20
)
RETURNS TABLE (
  id bigint,
  created_at timestamptz,
  created_by bigint,
  modified_at timestamptz,
  published_at timestamptz,
  is_draft boolean,
  comment_count bigint,
  body text,
  slug text,
  summary text,
  tags bigint[],
  title text,
  total_views bigint,
  hero_image json,
  email_content_reach bigint,
  total_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    n.id,
    n.created_at,
    n.created_by,
    n.modified_at,
    n.published_at,
    n.is_draft,
    n.comment_count,
    n.body,
    n.slug,
    n.summary,
    n.tags,
    n.title,
    n.total_views,
    n.hero_image,
    n.email_content_reach,
    COUNT(*) OVER () AS total_count
  FROM news n
  WHERE
    n.is_draft = false
    AND (
      p_is_admin
      OR NOT EXISTS (
        -- news has ANY badge restriction
        SELECT 1 FROM news_badges_relations nbr
        WHERE nbr.news_id = n.id
      )
      OR (
        -- news has badge restrictions AND user has at least one matching badge
        p_user_profile_id IS NOT NULL
        AND EXISTS (
          SELECT 1
          FROM news_badges_relations nbr
          JOIN profile_badges_relations pbr
            ON pbr.profile_badge_id = nbr.profile_badge_id
          WHERE nbr.news_id = n.id
            AND pbr.profile_id = p_user_profile_id
        )
      )
    )
    AND (
      p_search IS NULL
      OR to_tsvector('english', n.title || ' ' || n.body) @@ plainto_tsquery('english', p_search)
    )
  ORDER BY
    CASE WHEN p_sort = 'Newest'       THEN n.published_at   END DESC NULLS LAST,
    CASE WHEN p_sort = 'Comments'     THEN n.comment_count  END DESC NULLS LAST,
    CASE WHEN p_sort = 'LeastComments' THEN n.comment_count END ASC  NULLS LAST,
    n.published_at DESC  -- stable tiebreaker
  LIMIT p_limit
  OFFSET p_skip;
$$;
