CREATE TABLE IF NOT EXISTS "public"."organisation_signup_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text" NOT NULL,
    "image_url" "text",
    "tenant_id" "text" NOT NULL UNIQUE
);

ALTER TABLE "public"."organisation_signup_settings" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."organisation_signup_settings" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));
