-- Tracks auth accounts that chose the organisation sign-up path but have not
-- submitted their application yet. The profile row is only created on
-- submission, at which point this row is deleted.
CREATE TABLE IF NOT EXISTS "public"."organisation_applications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "auth_id" "uuid" NOT NULL,
    "tenant_id" "text" NOT NULL,
    CONSTRAINT "organisation_applications_auth_id_tenant_id_key" UNIQUE ("auth_id", "tenant_id")
);

ALTER TABLE ONLY "public"."organisation_applications"
    ADD CONSTRAINT "organisation_applications_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."organisation_applications" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."organisation_applications" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));
