CREATE TABLE IF NOT EXISTS "public"."patreon_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tiers" "json",
    "tenant_id" "text"
);

ALTER TABLE "public"."patreon_settings" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."patreon_settings" USING (("tenant_id" = (("current_setting"('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));
