CREATE TABLE IF NOT EXISTS "public"."polls" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" "text" DEFAULT ''::"text" NOT NULL,
    "title" "text" NOT NULL,
    "single_choice" boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS "public"."poll_options" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" "text" DEFAULT ''::"text" NOT NULL,
    "description" "text" NOT NULL,
    "poll_id" bigint NOT NULL,
    "vote_count" bigint NOT NULL DEFAULT 0
);

ALTER TABLE ONLY "public"."poll_options"
    ADD CONSTRAINT "poll_option_of_fkey" FOREIGN KEY ("poll_id") REFERENCES "public"."polls"("id") ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS "public"."poll_votes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" "text" DEFAULT ''::"text" NOT NULL,
    "poll_option_id" bigint NOT NULL,
    "profile_id" bigint NOT NULL
);

ALTER TABLE ONLY "public"."poll_votes"
    ADD CONSTRAINT "vote_for_fkey" FOREIGN KEY ("poll_option_id") REFERENCES "public"."poll_options"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."poll_votes"
    ADD CONSTRAINT "voted_by_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."news"
    ADD COLUMN "poll" bigint;

ALTER TABLE "public"."news"
    ADD CONSTRAINT "news_poll_unique"
        UNIQUE ("poll");

ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_poll_fkey" FOREIGN KEY ("poll") REFERENCES "public"."polls"("id") ON UPDATE CASCADE ON DELETE SET NULL;

CREATE UNIQUE INDEX "poll_vote_unique"
    ON "public"."poll_votes"(profile_id, poll_option_id);

CREATE INDEX IF NOT EXISTS "poll_options_poll_id_idx"
    ON "public"."poll_options"(poll_id);

CREATE OR REPLACE FUNCTION update_vote_count()
    RETURNS TRIGGER AS $$
    DECLARE
        option_id bigint;
    BEGIN
        option_id := COALESCE(NEW.poll_option_id, OLD.poll_option_id);

        UPDATE poll_options
        SET vote_count = (
            SELECT COUNT(*)
            FROM poll_votes
            WHERE poll_option_id = option_id
        )
        WHERE id = option_id;

        RETURN COALESCE(NEW, OLD);
    END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER "update_vote_count" AFTER INSERT OR DELETE ON "public"."poll_votes" FOR EACH ROW EXECUTE FUNCTION "public"."update_vote_count"();

CREATE INDEX IF NOT EXISTS "poll_options_poll_id_idx" ON "public"."poll_options"(poll_id);
CREATE INDEX IF NOT EXISTS "poll_votes_profile_idx" ON "public"."poll_votes"(profile_id);
CREATE INDEX IF NOT EXISTS "poll_votes_option_idx" ON "public"."poll_votes"(poll_option_id);


CREATE OR REPLACE FUNCTION "public"."get_poll_with_permissions"(
    p_poll_id bigint,
    p_profile_id bigint DEFAULT NULL,
    p_is_admin boolean DEFAULT false
)
    RETURNS json
    LANGUAGE plpgsql
    AS $$
    DECLARE
        result json;
        v_has_voted boolean := false;
    BEGIN

        -- 1. Check if user has voted in this poll
        IF p_profile_id IS NOT NULL THEN
            SELECT EXISTS (
                SELECT 1
                FROM poll_votes v
                         JOIN poll_options o ON o.id = v.poll_option_id
                WHERE v.profile_id = p_profile_id
                  AND o.poll_id = p_poll_id
            )
            INTO v_has_voted;
        END IF;

        -- 2. Build result
        SELECT json_build_object(
                       'id', p.id,
                       'title', p.title,
                       'singleChoice', p.single_choice,
                       'hasVoted', COALESCE(v_has_voted, false),

                       'options',
                       (
                           SELECT json_agg(
                                          json_build_object(
                                                  'id', o.id,
                                                  'description', o.description,
                                                  'voteCount',
                                                  CASE
                                                      WHEN p_is_admin OR v_has_voted THEN o.vote_count
                                                  END,
                                                  'wasVotedByUser',
                                                  EXISTS (
                                                      SELECT 1
                                                      FROM poll_votes v
                                                      WHERE v.poll_option_id = o.id
                                                        AND v.profile_id = p_profile_id
                                                  )
                                          )
                                  )
                           FROM poll_options o
                           WHERE o.poll_id = p.id
                       )

               )
        INTO result
        FROM polls p
        WHERE p.id = p_poll_id;

        RETURN result;
    END;
$$;

-- RLS STUFF

ALTER TABLE polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_votes ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION is_poll_admin()
    RETURNS boolean
    LANGUAGE sql
    STABLE
    AS $$
    SELECT EXISTS (
        SELECT 1
        FROM profiles p
        WHERE p.auth_id = auth.uid()
          AND (
            'admin' = ANY(p.roles)
                OR 'editor' = ANY(p.roles)
            )
    );
$$;

-- TODO check if no longer needed:

CREATE POLICY "Polls are readable"
    ON polls
    FOR SELECT
    USING (true);

CREATE POLICY "Admins can create polls"
    ON polls
    FOR INSERT
    TO authenticated
    WITH CHECK (is_poll_admin());

CREATE POLICY "Admins can update polls"
    ON polls
    FOR UPDATE
    TO authenticated
    USING (is_poll_admin())
    WITH CHECK (is_poll_admin());

CREATE POLICY "Admins can delete polls"
    ON polls
    FOR DELETE
    TO authenticated
    USING (is_poll_admin());

CREATE POLICY "Poll options are readable"
    ON poll_options
    FOR SELECT
    USING (true);

CREATE POLICY "Admins can create options"
    ON poll_options
    FOR INSERT
    TO authenticated
    WITH CHECK (is_poll_admin());

CREATE POLICY "Admins can update options"
    ON poll_options
    FOR UPDATE
    TO authenticated
    USING (is_poll_admin())
    WITH CHECK (is_poll_admin());

CREATE POLICY "Admins can delete poll options"
    ON poll_options
    FOR DELETE
    TO authenticated
    USING (is_poll_admin());

CREATE POLICY "Authenticated users can vote"
    ON poll_votes
    FOR INSERT
    TO authenticated
    WITH CHECK (
    profile_id = (
        SELECT id FROM profiles WHERE auth_id = auth.uid()
    )
    );

CREATE POLICY "Users can read votes (for update_vote_count)"
    ON poll_votes
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Users can update poll options (for vote count)"
    ON poll_options
    FOR UPDATE
    TO authenticated
    USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE polls
    TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE poll_options
    TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE poll_votes
    TO authenticated;

GRANT USAGE, SELECT
    ON SEQUENCE polls_id_seq
    TO authenticated;

GRANT USAGE, SELECT
    ON SEQUENCE poll_options_id_seq
    TO authenticated;

GRANT USAGE, SELECT
    ON SEQUENCE poll_votes_id_seq
    TO authenticated;




GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE polls
    TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE poll_options
    TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE poll_votes
    TO anon;

GRANT USAGE, SELECT
    ON SEQUENCE polls_id_seq
    TO anon;

GRANT USAGE, SELECT
    ON SEQUENCE poll_options_id_seq
    TO anon;

GRANT USAGE, SELECT
    ON SEQUENCE poll_votes_id_seq
    TO anon;

