CREATE OR REPLACE FUNCTION public.get_user_questions(username_param text)
 RETURNS TABLE(id bigint, comment_count bigint, images json[], title text, slug text, total_useful bigint)
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    q.id,
    q.comment_count,
    q.images,
    q.title,
    q.slug,
    COALESCE(COUNT(uv.id), 0)::BIGINT AS total_useful
  FROM questions q
  INNER JOIN profiles p ON p.id = q.created_by
  LEFT JOIN useful_votes uv ON uv.content_id = q.id AND uv.content_type = 'questions'
  WHERE p.username = username_param
  AND (q.deleted IS NULL OR q.deleted = FALSE)
  GROUP BY q.id, q.title, q.slug;
END;
$function$
;

CREATE TABLE IF NOT EXISTS "public"."questions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "created_by" bigint,
    "deleted" boolean,
    "modified_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "comment_count" bigint DEFAULT '0'::bigint,
    "description" "text" NOT NULL,
    "moderation" "text",
    "slug" "text" NOT NULL,
    "previous_slugs" "text"[],
    "category" bigint,
    "tags" bigint[],
    "title" "text" NOT NULL,
    "total_views" bigint,
    "tenant_id" "text" NOT NULL,
    "fts" "tsvector" GENERATED ALWAYS AS ("to_tsvector"('"english"'::"regconfig", (("title" || ' '::"text") || "description"))) STORED,
    "images" "json"[],
    "legacy_id" "text",
    "is_draft" boolean DEFAULT false NOT NULL,
    "published_at" timestamp with time zone
);

CREATE OR REPLACE FUNCTION "public"."questions_search_fields"("public"."questions") RETURNS "text"
    LANGUAGE "sql"
    SET search_path = public, pg_temp
    AS $_$
  SELECT $1.title || ' ' || $1.description;
$_$;

CREATE OR REPLACE FUNCTION public.get_questions(search_query text DEFAULT NULL::text, category_id bigint DEFAULT NULL::bigint, sort_by text DEFAULT 'Newest'::text, limit_val integer DEFAULT 20, offset_val integer DEFAULT 0)
 RETURNS TABLE(id bigint, created_at timestamp with time zone, created_by bigint, modified_at timestamp with time zone, published_at timestamp with time zone, description text, slug text, category json, tags bigint[], title text, total_views bigint, is_draft boolean, comment_count bigint, images json[], author json)
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  ts_query tsquery;
BEGIN
  IF search_query IS NOT NULL THEN
    -- Split search query into words, sanitize each with plainto_tsquery, then add prefix matching
    ts_query := to_tsquery('english', 
      array_to_string(
        ARRAY(
          SELECT regexp_replace(
            plainto_tsquery('english', word)::text,
            '''(\w+)''',
            '''\1'':*',
            'g'
          )
          FROM unnest(string_to_array(trim(search_query), ' ')) AS word
          WHERE word != ''
        ),
        ' & '
      )
    );
  END IF;

  RETURN QUERY
  SELECT
    q.id,
    q.created_at,
    q.created_by,
    q.modified_at,
    q.published_at,
    q.description,
    q.slug,
    (SELECT json_build_object('id', c.id, 'name', c.name) FROM categories c WHERE c.id = q.category) AS category,
    q.tags,
    q.title,
    q.total_views,
    q.is_draft,
    q.comment_count,
    q.images,
    (SELECT json_build_object(
      'id', p.id,
      'display_name', p.display_name,
      'username', p.username,
      'photo', p.photo,
      'country', p.country,
      'badges', COALESCE(
        (SELECT json_agg(
          json_build_object(
            'id', pb.id,
            'name', pb.name,
            'display_name', pb.display_name,
            'image_url', pb.image_url,
            'action_url', pb.action_url
          )
        )
        FROM profile_badges_relations pbr
        JOIN profile_badges pb ON pb.id = pbr.profile_badge_id
        WHERE pbr.profile_id = p.id),
        '[]'::json
      )
    ) FROM profiles p WHERE p.id = q.created_by) AS author
  FROM questions q
  JOIN profiles prof ON prof.id = q.created_by
  WHERE
    (search_query IS NULL OR
     q.fts @@ ts_query OR
     prof.username ILIKE '%' || search_query || '%'
    ) AND
    (category_id IS NULL OR q.category = category_id) AND
    q.is_draft = FALSE AND
    (q.deleted IS NULL OR q.deleted = FALSE)
  ORDER BY
    CASE WHEN search_query IS NOT NULL THEN ts_rank_cd(q.fts, ts_query) END DESC NULLS LAST,
    CASE
      WHEN sort_by = 'Newest' THEN extract(epoch from q.published_at)
      WHEN sort_by = 'Comments' THEN q.comment_count
      ELSE 0
    END DESC NULLS LAST,
    CASE
      WHEN sort_by = 'LeastComments' THEN q.comment_count
    END ASC NULLS LAST,
    q.published_at DESC
  LIMIT limit_val OFFSET offset_val;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_questions_count(search_query text DEFAULT NULL::text, category_id integer DEFAULT NULL::integer)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  ts_query tsquery;
BEGIN
  IF search_query IS NOT NULL THEN
    -- Split search query into words, sanitize each with plainto_tsquery, then add prefix matching
    ts_query := to_tsquery('english', 
      array_to_string(
        ARRAY(
          SELECT regexp_replace(
            plainto_tsquery('english', word)::text,
            '''(\w+)''',
            '''\1'':*',
            'g'
          )
          FROM unnest(string_to_array(trim(search_query), ' ')) AS word
          WHERE word != ''
        ),
        ' & '
      )
    );
  END IF;

  RETURN (
    SELECT COUNT(*)
    FROM questions q
    INNER JOIN profiles prof ON prof.id = q.created_by
    WHERE
      (search_query IS NULL OR
       q.fts @@ ts_query OR
       prof.username ILIKE '%' || search_query || '%'
      ) AND
      (category_id IS NULL OR q.category = category_id) AND
      q.is_draft = FALSE AND
      (q.deleted IS NULL OR q.deleted = FALSE)
  );
END;
$function$
;

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "unique_tenant_slug" UNIQUE ("tenant_id", "slug");

CREATE INDEX "questions_category_idx" ON "public"."questions" USING "btree" ("category");
CREATE INDEX "questions_created_by_idx" ON "public"."questions" USING "btree" ("created_by");
CREATE INDEX "questions_deleted_moderation_category_total_views_tags_crea_idx" ON "public"."questions" USING "btree" ("deleted", "moderation", "category", "total_views", "tags", "created_at", "comment_count", "created_by");
CREATE INDEX "questions_tags_idx" ON "public"."questions" USING "gin" ("tags");

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "question_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."categories"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."questions" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."questions" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));
