CREATE TABLE IF NOT EXISTS "public"."remakes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "modified_at" timestamp with time zone,
    "project_id" bigint NOT NULL,
    "created_by" bigint NOT NULL,
    "description" "text",
    "images" "json" NOT NULL,
    "tenant_id" "text" NOT NULL
);

ALTER TABLE ONLY "public"."remakes"
    ADD CONSTRAINT "remakes_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."remakes"
    ADD CONSTRAINT "remakes_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "remakes_project_id_created_at_idx" ON "public"."remakes"("project_id", "created_at" DESC);

ALTER TABLE "public"."remakes" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."remakes" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE "public"."remakes"
    TO "authenticated";

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE "public"."remakes"
    TO "anon";

GRANT USAGE, SELECT
    ON SEQUENCE "public"."remakes_id_seq"
    TO "authenticated";

GRANT USAGE, SELECT
    ON SEQUENCE "public"."remakes_id_seq"
    TO "anon";
