CREATE TABLE IF NOT EXISTS "public"."stripe_customers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "auth_id" "uuid" NOT NULL,
    "stripe_customer_id" "text" NOT NULL,
    "tenant_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    CONSTRAINT "stripe_customers_auth_id_tenant_id_key" UNIQUE ("auth_id", "tenant_id"),
    CONSTRAINT "stripe_customers_stripe_customer_id_tenant_id_key" UNIQUE ("stripe_customer_id", "tenant_id")
);

CREATE INDEX "idx_stripe_customers_auth_id" ON "public"."stripe_customers" USING "btree" ("auth_id");
CREATE INDEX "idx_stripe_customers_stripe_customer_id" ON "public"."stripe_customers" USING "btree" ("stripe_customer_id");
CREATE INDEX "idx_stripe_customers_tenant_id" ON "public"."stripe_customers" USING "btree" ("tenant_id");

ALTER TABLE ONLY "public"."stripe_customers"
    ADD CONSTRAINT "stripe_customers_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."stripe_customers" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."stripe_customers" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

CREATE TABLE IF NOT EXISTS "public"."stripe_badge_products" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "stripe_product_id" "text" NOT NULL UNIQUE,
    "name" "text" NOT NULL DEFAULT '',
    "badge_id" bigint NOT NULL,
    "tenant_id" "text" NOT NULL,
    CONSTRAINT "stripe_badge_products_badge_id_fkey"
      FOREIGN KEY ("badge_id") REFERENCES "public"."profile_badges"("id")
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX "idx_stripe_badge_products_stripe_product_id" ON "public"."stripe_badge_products" USING "btree" ("stripe_product_id");
CREATE INDEX "idx_stripe_badge_products_badge_id" ON "public"."stripe_badge_products" USING "btree" ("badge_id");
CREATE INDEX "idx_stripe_badge_products_tenant_id" ON "public"."stripe_badge_products" USING "btree" ("tenant_id");

ALTER TABLE "public"."stripe_badge_products" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."stripe_badge_products" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

CREATE TABLE IF NOT EXISTS "public"."stripe_tier_config" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "badge_id" bigint NOT NULL,
    "description" "text" NOT NULL,
    "color" "text" NOT NULL,
    "thank_you_image_url" "text",
    "tenant_id" "text" NOT NULL,
    CONSTRAINT "stripe_tier_config_badge_id_tenant_id_key" UNIQUE ("badge_id", "tenant_id"),
    CONSTRAINT "stripe_tier_config_badge_id_fkey"
      FOREIGN KEY ("badge_id") REFERENCES "public"."profile_badges"("id")
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX "idx_stripe_tier_config_badge_id" ON "public"."stripe_tier_config" USING "btree" ("badge_id");
CREATE INDEX "idx_stripe_tier_config_tenant_id" ON "public"."stripe_tier_config" USING "btree" ("tenant_id");

ALTER TABLE "public"."stripe_tier_config" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."stripe_tier_config" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));

GRANT SELECT ON TABLE "public"."stripe_tier_config" TO "anon";
GRANT SELECT ON TABLE "public"."stripe_tier_config" TO "authenticated";

CREATE OR REPLACE FUNCTION "public"."read_secret"("secret_name" "text")
RETURNS "text"
LANGUAGE "plpgsql" SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  secret_value text;
BEGIN
  SELECT decrypted_secret INTO secret_value
  FROM vault.decrypted_secrets
  WHERE name = secret_name
  LIMIT 1;

  RETURN secret_value;
END;
$$;

REVOKE EXECUTE ON FUNCTION "public"."read_secret"("text") FROM "anon";
REVOKE EXECUTE ON FUNCTION "public"."read_secret"("text") FROM "authenticated";

-- RPC function to list supporters (profiles holding a badge backed by a stripe tier config), including email from auth.users
CREATE OR REPLACE FUNCTION get_supporters(p_tenant_id text)
RETURNS TABLE (
  profile_id bigint,
  username text,
  display_name text,
  email text,
  tier_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT
    p.id AS profile_id,
    p.username,
    p.display_name,
    au.email::text,
    pb.display_name AS tier_name
  FROM stripe_tier_config stc
  INNER JOIN profile_badges pb ON pb.id = stc.badge_id
  INNER JOIN profile_badges_relations pbr ON pbr.profile_badge_id = pb.id
  INNER JOIN profiles p ON p.id = pbr.profile_id
  LEFT JOIN auth.users au ON au.id = p.auth_id
  WHERE stc.tenant_id = p_tenant_id
    AND pbr.tenant_id = p_tenant_id
    AND p.tenant_id = p_tenant_id;
END;
$$;
