CREATE TABLE IF NOT EXISTS "public"."stripe_customers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "auth_id" "uuid" NOT NULL,
    "stripe_customer_id" "text" NOT NULL,
    "tenant_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL
);

CREATE INDEX "idx_stripe_customers_auth_id" ON "public"."stripe_customers" USING "btree" ("auth_id");
CREATE INDEX "idx_stripe_customers_stripe_customer_id" ON "public"."stripe_customers" USING "btree" ("stripe_customer_id");
CREATE INDEX "idx_stripe_customers_tenant_id" ON "public"."stripe_customers" USING "btree" ("tenant_id");

ALTER TABLE ONLY "public"."stripe_customers"
    ADD CONSTRAINT "stripe_customers_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."stripe_customers" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."stripe_customers" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));
