-- Stripe tier configuration table
-- Manages subscription tier definitions used for premium profile badges.
-- The profile_badges.premium_tier column references tiers defined here.

CREATE TABLE IF NOT EXISTS "public"."stripe_tier_config" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tenant_id" "text" NOT NULL,
    "stripe_price_id" "text" NOT NULL,
    "badge_id" bigint
);

ALTER TABLE ONLY "public"."stripe_tier_config"
    ADD CONSTRAINT "stripe_tier_config_badge_id_fkey" FOREIGN KEY ("badge_id") REFERENCES "public"."profile_badges"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."stripe_tier_config" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."stripe_tier_config"
    AS PERMISSIVE FOR ALL TO public
    USING (("tenant_id" = ((SELECT current_setting('request.headers'::text, true))::json ->> 'x-tenant-id'::text)));
