CREATE TABLE IF NOT EXISTS "public"."subscribers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "user_id" bigint NOT NULL,
    "content_id" bigint NOT NULL,
    "content_type" "text" NOT NULL,
    "tenant_id" "text" NOT NULL
);

ALTER TABLE ONLY "public"."subscribers"
    ADD CONSTRAINT "subscribers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."subscribers" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."subscribers" USING (("tenant_id" = (SELECT (("current_setting"('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text"))));
