CREATE TABLE IF NOT EXISTS "public"."tenant_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "site_name" "text" NOT NULL,
    "site_url" "text" NOT NULL,
    "message_sign_off" "text",
    "tenant_id" "text" NOT NULL,
    "email_from" "text",
    "site_image" "text"
);

ALTER TABLE "public"."tenant_settings" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."tenant_settings" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));
