CREATE TABLE IF NOT EXISTS "public"."tenant_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "site_name" "text" NOT NULL,
    "site_description" "text",
    "site_url" "text" NOT NULL,
    "message_sign_off" "text",
    "tenant_id" "text" NOT NULL,
    "email_from" "text",
    "site_image" "text",
    "site_favicon" "text",
    "donation_settings" JSON,
    "no_messaging" BOOLEAN NOT NULL DEFAULT false,
    "library_heading" "text",
    "academy_resource" "text",
    "profile_guidelines" "text",
    "questions_guidelines" "text",
    "supported_modules" "text",
    "patreon_id" "text",
    "ga_tracking_id" "text",
    "pwa_icons" "jsonb",
    CONSTRAINT "check_pwa_icons_schema" CHECK (
        "pwa_icons" IS NULL
        OR (
            jsonb_typeof("pwa_icons") = 'object'
            AND "pwa_icons" - ARRAY['16','32','192','256','512'] = '{}'::jsonb
            AND ("pwa_icons"->>'16')  IS NOT NULL
            AND ("pwa_icons"->>'32')  IS NOT NULL
            AND ("pwa_icons"->>'192') IS NOT NULL
            AND ("pwa_icons"->>'256') IS NOT NULL
            AND ("pwa_icons"->>'512') IS NOT NULL
            AND jsonb_typeof("pwa_icons"->'16')  = 'string'
            AND jsonb_typeof("pwa_icons"->'32')  = 'string'
            AND jsonb_typeof("pwa_icons"->'192') = 'string'
            AND jsonb_typeof("pwa_icons"->'256') = 'string'
            AND jsonb_typeof("pwa_icons"->'512') = 'string'
        )
    )
);

ALTER TABLE "public"."tenant_settings" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."tenant_settings" USING (("tenant_id" = ((SELECT current_setting('request.headers'::"text", true))::"json" ->> 'x-tenant-id'::"text")));
