export const MAX_PIN_LENGTH = 70
export const MEMBER_PROFILE_DESCRIPTION_MAX_LENGTH = 500
export const GROUP_PROFILE_DESCRIPTION_MAX_LENGTH = 2000
export const DEFAULT_PUBLIC_CONTACT_PREFERENCE = true
