export const HOWTO_STEP_DESCRIPTION_MIN_LENGTH = 100
export const HOWTO_STEP_DESCRIPTION_MAX_LENGTH = 1000
export const HOWTO_MAX_LENGTH = 1000
export const HOWTO_MIN_REQUIRED_STEPS = 3
export const HOWTO_TITLE_MIN_LENGTH = 5
export const HOWTO_TITLE_MAX_LENGTH = 50
export const MAX_LINK_LENGTH = 2000
