create table "public"."upgrade_badge" (
    "id" bigint generated by default as identity not null,
    "action_label" text not null,
    "badge_id" bigint not null,
    "is_space" boolean not null,
    "action_url" text not null,
    "tenant_id" text not null
);


alter table "public"."upgrade_badge" enable row level security;

CREATE INDEX idx_upgrade_badge_is_space ON public.upgrade_badge USING btree (is_space);

CREATE INDEX idx_upgrade_badge_tenant_id ON public.upgrade_badge USING btree (tenant_id);

CREATE UNIQUE INDEX upgrade_badge_pkey ON public.upgrade_badge USING btree (id);

alter table "public"."upgrade_badge" add constraint "upgrade_badge_pkey" PRIMARY KEY using index "upgrade_badge_pkey";

alter table "public"."upgrade_badge" add constraint "upgrade_badge_badge_id_fkey" FOREIGN KEY (badge_id) REFERENCES profile_badges(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."upgrade_badge" validate constraint "upgrade_badge_badge_id_fkey";

grant delete on table "public"."upgrade_badge" to "anon";

grant insert on table "public"."upgrade_badge" to "anon";

grant references on table "public"."upgrade_badge" to "anon";

grant select on table "public"."upgrade_badge" to "anon";

grant trigger on table "public"."upgrade_badge" to "anon";

grant truncate on table "public"."upgrade_badge" to "anon";

grant update on table "public"."upgrade_badge" to "anon";

grant delete on table "public"."upgrade_badge" to "authenticated";

grant insert on table "public"."upgrade_badge" to "authenticated";

grant references on table "public"."upgrade_badge" to "authenticated";

grant select on table "public"."upgrade_badge" to "authenticated";

grant trigger on table "public"."upgrade_badge" to "authenticated";

grant truncate on table "public"."upgrade_badge" to "authenticated";

grant update on table "public"."upgrade_badge" to "authenticated";

grant delete on table "public"."upgrade_badge" to "service_role";

grant insert on table "public"."upgrade_badge" to "service_role";

grant references on table "public"."upgrade_badge" to "service_role";

grant select on table "public"."upgrade_badge" to "service_role";

grant trigger on table "public"."upgrade_badge" to "service_role";

grant truncate on table "public"."upgrade_badge" to "service_role";

grant update on table "public"."upgrade_badge" to "service_role";

create policy "tenant_isolation"
on "public"."upgrade_badge"
as permissive
for all
to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));



