create table "public"."patreon_settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "tenant_tier_id" text,
    "oa_basic_tier_id" text,
    "oa_plus_tier_id" text,
    "oa_magic_tier_id" text,
    "tenant_id" text
);

alter table "public"."patreon_settings" enable row level security;

CREATE UNIQUE INDEX patreon_settings_pkey ON public.patreon_settings USING btree (id);

alter table "public"."patreon_settings" add constraint "patreon_settings_pkey" PRIMARY KEY using index "patreon_settings_pkey";

grant delete on table "public"."patreon_settings" to "anon";

grant insert on table "public"."patreon_settings" to "anon";

grant references on table "public"."patreon_settings" to "anon";

grant select on table "public"."patreon_settings" to "anon";

grant trigger on table "public"."patreon_settings" to "anon";

grant truncate on table "public"."patreon_settings" to "anon";

grant update on table "public"."patreon_settings" to "anon";

grant delete on table "public"."patreon_settings" to "authenticated";

grant insert on table "public"."patreon_settings" to "authenticated";

grant references on table "public"."patreon_settings" to "authenticated";

grant select on table "public"."patreon_settings" to "authenticated";

grant trigger on table "public"."patreon_settings" to "authenticated";

grant truncate on table "public"."patreon_settings" to "authenticated";

grant update on table "public"."patreon_settings" to "authenticated";

grant delete on table "public"."patreon_settings" to "service_role";

grant insert on table "public"."patreon_settings" to "service_role";

grant references on table "public"."patreon_settings" to "service_role";

grant select on table "public"."patreon_settings" to "service_role";

grant trigger on table "public"."patreon_settings" to "service_role";

grant truncate on table "public"."patreon_settings" to "service_role";

grant update on table "public"."patreon_settings" to "service_role";

create policy "tenant_isolation"
on "public"."patreon_settings"
as permissive
for all
to public
using ((tenant_id = ((current_setting('request.headers'::text, true))::json ->> 'x-tenant-id'::text)));
