create table "public"."notifications_preferences" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "comments" boolean not null,
    "replies" boolean not null,
    "tenant_id" text not null
);


alter table "public"."notifications_preferences" enable row level security;

CREATE UNIQUE INDEX notifications_preferences_pkey ON public.notifications_preferences USING btree (id);

alter table "public"."notifications_preferences" add constraint "notifications_preferences_pkey" PRIMARY KEY using index "notifications_preferences_pkey";

alter table "public"."notifications_preferences" add constraint "notifications_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."notifications_preferences" validate constraint "notifications_preferences_user_id_fkey";

grant delete on table "public"."notifications_preferences" to "anon";

grant insert on table "public"."notifications_preferences" to "anon";

grant references on table "public"."notifications_preferences" to "anon";

grant select on table "public"."notifications_preferences" to "anon";

grant trigger on table "public"."notifications_preferences" to "anon";

grant truncate on table "public"."notifications_preferences" to "anon";

grant update on table "public"."notifications_preferences" to "anon";

grant delete on table "public"."notifications_preferences" to "authenticated";

grant insert on table "public"."notifications_preferences" to "authenticated";

grant references on table "public"."notifications_preferences" to "authenticated";

grant select on table "public"."notifications_preferences" to "authenticated";

grant trigger on table "public"."notifications_preferences" to "authenticated";

grant truncate on table "public"."notifications_preferences" to "authenticated";

grant update on table "public"."notifications_preferences" to "authenticated";

grant delete on table "public"."notifications_preferences" to "service_role";

grant insert on table "public"."notifications_preferences" to "service_role";

grant references on table "public"."notifications_preferences" to "service_role";

grant select on table "public"."notifications_preferences" to "service_role";

grant trigger on table "public"."notifications_preferences" to "service_role";

grant truncate on table "public"."notifications_preferences" to "service_role";

grant update on table "public"."notifications_preferences" to "service_role";

create policy "tenant_isolation"
on "public"."notifications_preferences"
as permissive
for all
to public
using ((tenant_id = ((current_setting('request.headers'::text, true))::json ->> 'x-tenant-id'::text)));



