create table "public"."stripe_badge_products" (
    "id" bigint generated by default as identity not null,
    "stripe_product_id" text not null,
    "badge_id" bigint not null,
    "tenant_id" text not null
);


alter table "public"."stripe_badge_products" enable row level security;

CREATE INDEX idx_stripe_badge_products_badge_id ON public.stripe_badge_products USING btree (badge_id);

CREATE INDEX idx_stripe_badge_products_stripe_product_id ON public.stripe_badge_products USING btree (stripe_product_id);

CREATE INDEX idx_stripe_badge_products_tenant_id ON public.stripe_badge_products USING btree (tenant_id);

CREATE UNIQUE INDEX stripe_badge_products_pkey ON public.stripe_badge_products USING btree (id);

CREATE UNIQUE INDEX stripe_badge_products_stripe_product_id_key ON public.stripe_badge_products USING btree (stripe_product_id);

alter table "public"."stripe_badge_products" add constraint "stripe_badge_products_pkey" PRIMARY KEY using index "stripe_badge_products_pkey";

alter table "public"."stripe_badge_products" add constraint "stripe_badge_products_badge_id_fkey" FOREIGN KEY (badge_id) REFERENCES profile_badges(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."stripe_badge_products" validate constraint "stripe_badge_products_badge_id_fkey";

alter table "public"."stripe_badge_products" add constraint "stripe_badge_products_stripe_product_id_key" UNIQUE using index "stripe_badge_products_stripe_product_id_key";

grant delete on table "public"."stripe_badge_products" to "anon";

grant insert on table "public"."stripe_badge_products" to "anon";

grant references on table "public"."stripe_badge_products" to "anon";

grant select on table "public"."stripe_badge_products" to "anon";

grant trigger on table "public"."stripe_badge_products" to "anon";

grant truncate on table "public"."stripe_badge_products" to "anon";

grant update on table "public"."stripe_badge_products" to "anon";

grant delete on table "public"."stripe_badge_products" to "authenticated";

grant insert on table "public"."stripe_badge_products" to "authenticated";

grant references on table "public"."stripe_badge_products" to "authenticated";

grant select on table "public"."stripe_badge_products" to "authenticated";

grant trigger on table "public"."stripe_badge_products" to "authenticated";

grant truncate on table "public"."stripe_badge_products" to "authenticated";

grant update on table "public"."stripe_badge_products" to "authenticated";

grant delete on table "public"."stripe_badge_products" to "service_role";

grant insert on table "public"."stripe_badge_products" to "service_role";

grant references on table "public"."stripe_badge_products" to "service_role";

grant select on table "public"."stripe_badge_products" to "service_role";

grant trigger on table "public"."stripe_badge_products" to "service_role";

grant truncate on table "public"."stripe_badge_products" to "service_role";

grant update on table "public"."stripe_badge_products" to "service_role";

create policy "tenant_isolation"
on "public"."stripe_badge_products"
as permissive
for all
to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));
