  create table "public"."poll_options" (
    "id" bigint generated by default as identity not null,
    "tenant_id" text not null default ''::text,
    "description" text not null,
    "poll_id" bigint,
    "vote_count" bigint not null default 0
      );


alter table "public"."poll_options" enable row level security;


  create table "public"."poll_votes" (
    "id" bigint generated by default as identity not null,
    "tenant_id" text not null default ''::text,
    "poll_option_id" bigint,
    "profile_id" bigint
      );


alter table "public"."poll_votes" enable row level security;


  create table "public"."polls" (
    "id" bigint generated by default as identity not null,
    "tenant_id" text not null default ''::text,
    "title" text not null,
    "single_choice" boolean not null default true
      );


alter table "public"."polls" enable row level security;

alter table "public"."news" add column "poll" bigint;

alter table "public"."news_badges_relations" enable row level security;

CREATE UNIQUE INDEX news_poll_unique ON public.news USING btree (poll);

CREATE UNIQUE INDEX poll_options_pkey ON public.poll_options USING btree (id);

CREATE INDEX poll_options_poll_id_idx ON public.poll_options USING btree (poll_id);

CREATE UNIQUE INDEX poll_vote_unique ON public.poll_votes USING btree (profile_id, poll_option_id);

CREATE INDEX poll_votes_option_idx ON public.poll_votes USING btree (poll_option_id);

CREATE UNIQUE INDEX poll_votes_pkey ON public.poll_votes USING btree (id);

CREATE INDEX poll_votes_profile_idx ON public.poll_votes USING btree (profile_id);

CREATE UNIQUE INDEX polls_pkey ON public.polls USING btree (id);

alter table "public"."poll_options" add constraint "poll_options_pkey" PRIMARY KEY using index "poll_options_pkey";

alter table "public"."poll_votes" add constraint "poll_votes_pkey" PRIMARY KEY using index "poll_votes_pkey";

alter table "public"."polls" add constraint "polls_pkey" PRIMARY KEY using index "polls_pkey";

alter table "public"."news" add constraint "news_poll_fkey" FOREIGN KEY (poll) REFERENCES public.polls(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."news" validate constraint "news_poll_fkey";

alter table "public"."news" add constraint "news_poll_unique" UNIQUE using index "news_poll_unique";

alter table "public"."poll_options" add constraint "poll_option_of_fkey" FOREIGN KEY (poll_id) REFERENCES public.polls(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."poll_options" validate constraint "poll_option_of_fkey";

alter table "public"."poll_votes" add constraint "vote_for_fkey" FOREIGN KEY (poll_option_id) REFERENCES public.poll_options(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."poll_votes" validate constraint "vote_for_fkey";

alter table "public"."poll_votes" add constraint "voted_by_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."poll_votes" validate constraint "voted_by_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_poll_with_permissions(p_poll_id bigint, p_profile_id bigint DEFAULT NULL::bigint, p_is_admin boolean DEFAULT false)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
    DECLARE
        result json;
        v_has_voted boolean := false;
    BEGIN

        -- 1. Check if user has voted in this poll
        IF p_profile_id IS NOT NULL THEN
            SELECT EXISTS (
                SELECT 1
                FROM poll_votes v
                         JOIN poll_options o ON o.id = v.poll_option_id
                WHERE v.profile_id = p_profile_id
                  AND o.poll_id = p_poll_id
            )
            INTO v_has_voted;
        END IF;

        -- 2. Build result
        SELECT json_build_object(
                       'id', p.id,
                       'title', p.title,
                       'singleChoice', p.single_choice,
                       'hasVoted', COALESCE(v_has_voted, false),

                       'options',
                       (
                           SELECT json_agg(
                                          json_build_object(
                                                  'id', o.id,
                                                  'description', o.description,
                                                  'voteCount',
                                                  CASE
                                                      WHEN p_is_admin OR v_has_voted THEN o.vote_count
                                                  END,
                                                  'wasVotedByUser',
                                                  EXISTS (
                                                      SELECT 1
                                                      FROM poll_votes v
                                                      WHERE v.poll_option_id = o.id
                                                        AND v.profile_id = p_profile_id
                                                  )
                                          )
                                  )
                           FROM poll_options o
                           WHERE o.poll_id = p.id
                       )

               )
        INTO result
        FROM polls p
        WHERE p.id = p_poll_id;

        RETURN result;
    END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_poll_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
    SELECT EXISTS (
        SELECT 1
        FROM profiles p
        WHERE p.auth_id = auth.uid()
          AND (
            'admin' = ANY(p.roles)
                OR 'editor' = ANY(p.roles)
            )
    );
$function$
;

CREATE OR REPLACE FUNCTION public.update_vote_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    DECLARE
        option_id bigint;
    BEGIN
        option_id := COALESCE(NEW.poll_option_id, OLD.poll_option_id);

        UPDATE poll_options
        SET vote_count = (
            SELECT COUNT(*)
            FROM poll_votes
            WHERE poll_option_id = option_id
        )
        WHERE id = option_id;

        RETURN COALESCE(NEW, OLD);
    END;
$function$
;

grant delete on table "public"."poll_options" to "anon";

grant insert on table "public"."poll_options" to "anon";

grant references on table "public"."poll_options" to "anon";

grant select on table "public"."poll_options" to "anon";

grant trigger on table "public"."poll_options" to "anon";

grant truncate on table "public"."poll_options" to "anon";

grant update on table "public"."poll_options" to "anon";

grant delete on table "public"."poll_options" to "authenticated";

grant insert on table "public"."poll_options" to "authenticated";

grant references on table "public"."poll_options" to "authenticated";

grant select on table "public"."poll_options" to "authenticated";

grant trigger on table "public"."poll_options" to "authenticated";

grant truncate on table "public"."poll_options" to "authenticated";

grant update on table "public"."poll_options" to "authenticated";

grant references on table "public"."poll_options" to "service_role";

grant trigger on table "public"."poll_options" to "service_role";

grant truncate on table "public"."poll_options" to "service_role";

grant delete on table "public"."poll_votes" to "anon";

grant insert on table "public"."poll_votes" to "anon";

grant references on table "public"."poll_votes" to "anon";

grant select on table "public"."poll_votes" to "anon";

grant trigger on table "public"."poll_votes" to "anon";

grant truncate on table "public"."poll_votes" to "anon";

grant update on table "public"."poll_votes" to "anon";

grant delete on table "public"."poll_votes" to "authenticated";

grant insert on table "public"."poll_votes" to "authenticated";

grant references on table "public"."poll_votes" to "authenticated";

grant select on table "public"."poll_votes" to "authenticated";

grant trigger on table "public"."poll_votes" to "authenticated";

grant truncate on table "public"."poll_votes" to "authenticated";

grant update on table "public"."poll_votes" to "authenticated";

grant references on table "public"."poll_votes" to "service_role";

grant trigger on table "public"."poll_votes" to "service_role";

grant truncate on table "public"."poll_votes" to "service_role";

grant delete on table "public"."polls" to "anon";

grant insert on table "public"."polls" to "anon";

grant references on table "public"."polls" to "anon";

grant select on table "public"."polls" to "anon";

grant trigger on table "public"."polls" to "anon";

grant truncate on table "public"."polls" to "anon";

grant update on table "public"."polls" to "anon";

grant delete on table "public"."polls" to "authenticated";

grant insert on table "public"."polls" to "authenticated";

grant references on table "public"."polls" to "authenticated";

grant select on table "public"."polls" to "authenticated";

grant trigger on table "public"."polls" to "authenticated";

grant truncate on table "public"."polls" to "authenticated";

grant update on table "public"."polls" to "authenticated";

grant references on table "public"."polls" to "service_role";

grant trigger on table "public"."polls" to "service_role";

grant truncate on table "public"."polls" to "service_role";


  create policy "tenant_isolation"
  on "public"."poll_options"
  as permissive
  for all
  to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));



  create policy "tenant_isolation"
  on "public"."poll_votes"
  as permissive
  for all
  to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));



  create policy "tenant_isolation"
  on "public"."polls"
  as permissive
  for all
  to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));



CREATE TRIGGER update_vote_count AFTER INSERT OR DELETE ON public.poll_votes FOR EACH ROW EXECUTE FUNCTION public.update_vote_count();
