drop policy "tenant_isolation" on "public"."email_content_reach";

alter table "public"."news" drop constraint "news_email_content_reach_fkey";

alter table "public"."news" drop constraint "news_profile_badge_fkey";

alter table "public"."notifications_preferences" drop constraint "notifications_preferences_email_content_reach_fkey";

alter table "public"."email_content_reach" drop constraint "email_content_reach_pkey";

drop index if exists "public"."email_content_reach_pkey";

alter type "public"."notification_action_types" rename to "notification_action_types__old_version_to_be_dropped";

create type "public"."notification_action_types" as enum ('newComment', 'newContent');

alter type "public"."notification_content_types" rename to "notification_content_types__old_version_to_be_dropped";

create type "public"."notification_content_types" as enum ('news', 'research', 'researchUpdate', 'library', 'questions', 'comment', 'reply');

alter type "public"."notification_source_content_type" rename to "notification_source_content_type__old_version_to_be_dropped";

create type "public"."notification_source_content_type" as enum ('news', 'research', 'researchUpdate', 'library', 'questions');

create table "public"."news_badges_relations" (
  "id" bigint generated by default as identity not null,
  "news_id" bigint not null,
  "profile_badge_id" bigint not null,
  "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  "tenant_id" text not null
);

alter table "public"."news_badges_relations" enable row level security;

alter table "public"."notifications" alter column action_type type "public"."notification_action_types" using action_type::text::"public"."notification_action_types";

alter table "public"."notifications" alter column content_type type "public"."notification_content_types" using content_type::text::"public"."notification_content_types";

drop type "public"."notification_action_types__old_version_to_be_dropped";

drop type "public"."notification_content_types__old_version_to_be_dropped";

drop type "public"."notification_source_content_type__old_version_to_be_dropped";

alter table "public"."email_content_reach" disable row level security;

CREATE INDEX idx_news_badges_relations_badge_id ON public.news_badges_relations USING btree (profile_badge_id);

CREATE INDEX idx_news_badges_relations_news_badge ON public.news_badges_relations USING btree (news_id, profile_badge_id);

CREATE INDEX idx_news_badges_relations_news_id ON public.news_badges_relations USING btree (news_id);

CREATE INDEX idx_news_badges_relations_tenant_id ON public.news_badges_relations USING btree (tenant_id);

CREATE INDEX news_badges_relations_news_tenant_idx ON public.news_badges_relations USING btree (news_id, tenant_id);

CREATE UNIQUE INDEX news_badges_relations_pkey ON public.news_badges_relations USING btree (id);

alter table "public"."news_badges_relations" add constraint "news_badges_relations_pkey" PRIMARY KEY using index "news_badges_relations_pkey";

alter table "public"."news_badges_relations" add constraint "news_badges_relations_news_id_fkey" FOREIGN KEY (news_id) REFERENCES public.news(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_badges_relations" validate constraint "news_badges_relations_news_id_fkey";

alter table "public"."news_badges_relations" add constraint "news_badges_relations_profile_badge_id_fkey" FOREIGN KEY (profile_badge_id) REFERENCES public.profile_badges(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_badges_relations" validate constraint "news_badges_relations_profile_badge_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_news_feed(p_user_profile_id bigint DEFAULT NULL::bigint, p_is_admin boolean DEFAULT false, p_search text DEFAULT NULL::text, p_sort text DEFAULT 'Newest'::text, p_skip integer DEFAULT 0, p_limit integer DEFAULT 20)
 RETURNS TABLE(id bigint, created_at timestamp with time zone, created_by bigint, modified_at timestamp with time zone, published_at timestamp with time zone, is_draft boolean, comment_count bigint, body text, slug text, summary text, tags bigint[], title text, total_views bigint, hero_image json, email_content_reach bigint, total_count bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT
    n.id,
    n.created_at,
    n.created_by,
    n.modified_at,
    n.published_at,
    n.is_draft,
    n.comment_count,
    n.body,
    n.slug,
    n.summary,
    n.tags,
    n.title,
    n.total_views,
    n.hero_image,
    n.email_content_reach,
    COUNT(*) OVER () AS total_count
  FROM news n
  WHERE
    n.is_draft = false
    AND (
      p_is_admin
      OR NOT EXISTS (
        -- news has ANY badge restriction
        SELECT 1 FROM news_badges_relations nbr
        WHERE nbr.news_id = n.id
      )
      OR (
        -- news has badge restrictions AND user has at least one matching badge
        p_user_profile_id IS NOT NULL
        AND EXISTS (
          SELECT 1
          FROM news_badges_relations nbr
          JOIN profile_badges_relations pbr
            ON pbr.profile_badge_id = nbr.profile_badge_id
          WHERE nbr.news_id = n.id
            AND pbr.profile_id = p_user_profile_id
        )
      )
    )
    AND (
      p_search IS NULL
      OR to_tsvector('english', n.title || ' ' || n.body) @@ plainto_tsquery('english', p_search)
    )
  ORDER BY
    CASE WHEN p_sort = 'Newest'       THEN n.published_at   END DESC NULLS LAST,
    CASE WHEN p_sort = 'Comments'     THEN n.comment_count  END DESC NULLS LAST,
    CASE WHEN p_sort = 'LeastComments' THEN n.comment_count END ASC  NULLS LAST,
    n.published_at DESC  -- stable tiebreaker
  LIMIT p_limit
  OFFSET p_skip;
$function$
;

grant delete on table "public"."news_badges_relations" to "anon";

grant insert on table "public"."news_badges_relations" to "anon";

grant references on table "public"."news_badges_relations" to "anon";

grant select on table "public"."news_badges_relations" to "anon";

grant trigger on table "public"."news_badges_relations" to "anon";

grant truncate on table "public"."news_badges_relations" to "anon";

grant update on table "public"."news_badges_relations" to "anon";

grant delete on table "public"."news_badges_relations" to "authenticated";

grant insert on table "public"."news_badges_relations" to "authenticated";

grant references on table "public"."news_badges_relations" to "authenticated";

grant select on table "public"."news_badges_relations" to "authenticated";

grant trigger on table "public"."news_badges_relations" to "authenticated";

grant truncate on table "public"."news_badges_relations" to "authenticated";

grant update on table "public"."news_badges_relations" to "authenticated";

grant delete on table "public"."news_badges_relations" to "service_role";

grant insert on table "public"."news_badges_relations" to "service_role";

grant references on table "public"."news_badges_relations" to "service_role";

grant select on table "public"."news_badges_relations" to "service_role";

grant trigger on table "public"."news_badges_relations" to "service_role";

grant truncate on table "public"."news_badges_relations" to "service_role";

grant update on table "public"."news_badges_relations" to "service_role";

create policy "tenant_isolation"
  on "public"."news_badges_relations"
  as permissive
  for all
  to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));

INSERT INTO public.news_badges_relations (news_id, profile_badge_id, tenant_id)
SELECT id, profile_badge, tenant_id
FROM public.news
WHERE profile_badge IS NOT NULL;