alter table "public"."news" drop constraint "news_profile_badge_fkey";

create table "public"."news_badges_relations" (
  "id" bigint generated by default as identity not null,
  "news_id" bigint not null,
  "profile_badge_id" bigint not null,
  "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  "tenant_id" text not null
);

CREATE INDEX idx_news_badges_relations_badge_id ON public.news_badges_relations USING btree (profile_badge_id);

CREATE INDEX idx_news_badges_relations_news_badge ON public.news_badges_relations USING btree (news_id, profile_badge_id);

CREATE INDEX idx_news_badges_relations_news_id ON public.news_badges_relations USING btree (news_id);

CREATE INDEX idx_news_badges_relations_tenant_id ON public.news_badges_relations USING btree (tenant_id);

CREATE INDEX news_badges_relations_news_tenant_idx ON public.news_badges_relations USING btree (news_id, tenant_id);

CREATE UNIQUE INDEX news_badges_relations_pkey ON public.news_badges_relations USING btree (id);

alter table "public"."news_badges_relations" add constraint "news_badges_relations_pkey" PRIMARY KEY using index "news_badges_relations_pkey";

alter table "public"."news_badges_relations" add constraint "news_badges_relations_news_id_fkey" FOREIGN KEY (news_id) REFERENCES public.news(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_badges_relations" validate constraint "news_badges_relations_news_id_fkey";

alter table "public"."news_badges_relations" add constraint "news_badges_relations_profile_badge_id_fkey" FOREIGN KEY (profile_badge_id) REFERENCES public.profile_badges(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_badges_relations" validate constraint "news_badges_relations_profile_badge_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_news_feed(
  p_user_profile_id bigint DEFAULT NULL,  -- NULL = unauthenticated
  p_is_admin boolean DEFAULT false,
  p_search text DEFAULT NULL,
  p_sort text DEFAULT 'Newest',
  p_skip integer DEFAULT 0,
  p_limit integer DEFAULT 20
)
RETURNS TABLE (
  id bigint,
  created_at timestamptz,
  created_by bigint,
  modified_at timestamptz,
  published_at timestamptz,
  is_draft boolean,
  comment_count bigint,
  body text,
  slug text,
  summary text,
  tags bigint[],
  title text,
  total_views bigint,
  hero_image json,
  content_reach "public"."content_reach",
  profile_badges json,
  total_count bigint
)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT
    n.id,
    n.created_at,
    n.created_by,
    n.modified_at,
    n.published_at,
    n.is_draft,
    n.comment_count,
    n.body,
    n.slug,
    n.summary,
    n.tags,
    n.title,
    n.total_views,
    n.hero_image,
    n.content_reach,
    (
      SELECT COALESCE(
        json_agg(json_build_object('profile_badges', row_to_json(pb))),
        '[]'::json
      )
      FROM news_badges_relations nbr
      JOIN profile_badges pb ON pb.id = nbr.profile_badge_id
      WHERE nbr.news_id = n.id
    ) AS profile_badges,
    COUNT(*) OVER () AS total_count
  FROM news n
  WHERE
    n.is_draft = false
    AND (
      p_is_admin
      OR NOT EXISTS (
        -- news has ANY badge restriction
        SELECT 1 FROM news_badges_relations nbr
        WHERE nbr.news_id = n.id
      )
      OR (
        -- news has badge restrictions AND user has at least one matching badge
        p_user_profile_id IS NOT NULL
        AND EXISTS (
          SELECT 1
          FROM news_badges_relations nbr
          JOIN profile_badges_relations pbr
            ON pbr.profile_badge_id = nbr.profile_badge_id
          WHERE nbr.news_id = n.id
            AND pbr.profile_id = p_user_profile_id
        )
      )
    )
    AND (
      p_search IS NULL
      OR to_tsvector('english', n.title || ' ' || n.body) @@ plainto_tsquery('english', p_search)
    )
  ORDER BY
    CASE WHEN p_sort = 'Newest'       THEN n.published_at   END DESC NULLS LAST,
    CASE WHEN p_sort = 'Comments'     THEN n.comment_count  END DESC NULLS LAST,
    CASE WHEN p_sort = 'LeastComments' THEN n.comment_count END ASC  NULLS LAST,
    n.published_at DESC  -- stable tiebreaker
  LIMIT p_limit
  OFFSET p_skip;
$$;


grant delete on table "public"."news_badges_relations" to "anon";

grant insert on table "public"."news_badges_relations" to "anon";

grant references on table "public"."news_badges_relations" to "anon";

grant select on table "public"."news_badges_relations" to "anon";

grant trigger on table "public"."news_badges_relations" to "anon";

grant truncate on table "public"."news_badges_relations" to "anon";

grant update on table "public"."news_badges_relations" to "anon";

grant delete on table "public"."news_badges_relations" to "authenticated";

grant insert on table "public"."news_badges_relations" to "authenticated";

grant references on table "public"."news_badges_relations" to "authenticated";

grant select on table "public"."news_badges_relations" to "authenticated";

grant trigger on table "public"."news_badges_relations" to "authenticated";

grant truncate on table "public"."news_badges_relations" to "authenticated";

grant update on table "public"."news_badges_relations" to "authenticated";

grant delete on table "public"."news_badges_relations" to "service_role";

grant insert on table "public"."news_badges_relations" to "service_role";

grant references on table "public"."news_badges_relations" to "service_role";

grant select on table "public"."news_badges_relations" to "service_role";

grant trigger on table "public"."news_badges_relations" to "service_role";

grant truncate on table "public"."news_badges_relations" to "service_role";

grant update on table "public"."news_badges_relations" to "service_role";

create policy "tenant_isolation"
  on "public"."news_badges_relations"
  as permissive
  for all
  to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));

INSERT INTO public.news_badges_relations (news_id, profile_badge_id, tenant_id)
SELECT id, profile_badge, tenant_id
FROM public.news
WHERE profile_badge IS NOT NULL;