create table "public"."stripe_customers" (
  "id" bigint generated by default as identity not null,
  "auth_id" uuid not null,
  "stripe_customer_id" text not null,
  "tenant_id" text not null,
  "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  constraint "stripe_customers_pkey" primary key ("id"),
  constraint "stripe_customers_auth_id_fkey" foreign key ("auth_id") references "auth"."users"("id") on update cascade on delete cascade
);

create index "idx_stripe_customers_auth_id" on "public"."stripe_customers" using btree ("auth_id");
create index "idx_stripe_customers_stripe_customer_id" on "public"."stripe_customers" using btree ("stripe_customer_id");
create index "idx_stripe_customers_tenant_id" on "public"."stripe_customers" using btree ("tenant_id");

alter table "public"."stripe_customers" enable row level security;

create policy "tenant_isolation"
  on "public"."stripe_customers"
  as permissive
  for all
  to public
  using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));

grant select, insert, update, delete on table "public"."stripe_customers" to "anon";
grant select, insert, update, delete on table "public"."stripe_customers" to "authenticated";
grant select, insert, update, delete on table "public"."stripe_customers" to "service_role";
