
-- Ensure stripe_tier_config exists with correct structure.
-- This table was created by an old migration that was removed from the repo.
-- By declaring it here we make it part of the tracked schema (see schemas/stripe.sql).
CREATE TABLE IF NOT EXISTS "public"."stripe_tier_config" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tenant_id" "text" NOT NULL,
    "stripe_price_id" "text" NOT NULL,
    "badge_id" bigint
);

ALTER TABLE "public"."stripe_tier_config" DROP CONSTRAINT IF EXISTS "stripe_tier_config_badge_id_fkey";
ALTER TABLE "public"."stripe_tier_config"
    ADD CONSTRAINT "stripe_tier_config_badge_id_fkey"
    FOREIGN KEY ("badge_id") REFERENCES "public"."profile_badges"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."stripe_tier_config" ENABLE ROW LEVEL SECURITY;

-- Drop old policy and recreate in canonical form to eliminate diff noise.
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."stripe_tier_config";

CREATE POLICY "tenant_isolation" ON "public"."stripe_tier_config"
    AS PERMISSIVE FOR ALL TO public
    USING (("tenant_id" = ((SELECT current_setting('request.headers'::text, true))::json ->> 'x-tenant-id'::text)));
