CREATE TABLE "public"."stripe_tier_config" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "badge_id" bigint NOT NULL REFERENCES "public"."profile_badges"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "description" text NOT NULL,
    "color" text NOT NULL,
    "tenant_id" text NOT NULL,
    UNIQUE ("badge_id", "tenant_id")
);

ALTER TABLE "public"."stripe_tier_config" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "public"."stripe_tier_config"
AS PERMISSIVE FOR ALL TO public
USING ((tenant_id = ((current_setting('request.headers'::text, true))::json ->> 'x-tenant-id'::text)));

CREATE INDEX idx_stripe_tier_config_badge_id ON public.stripe_tier_config USING btree (badge_id);
CREATE INDEX idx_stripe_tier_config_tenant_id ON public.stripe_tier_config USING btree (tenant_id);
