create table "public"."organisation_applications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "auth_id" uuid not null,
    "tenant_id" text not null
);

alter table "public"."organisation_applications" enable row level security;

CREATE UNIQUE INDEX organisation_applications_pkey ON public.organisation_applications USING btree (id);

CREATE UNIQUE INDEX organisation_applications_auth_id_tenant_id_key ON public.organisation_applications USING btree (auth_id, tenant_id);

alter table "public"."organisation_applications" add constraint "organisation_applications_pkey" PRIMARY KEY using index "organisation_applications_pkey";

alter table "public"."organisation_applications" add constraint "organisation_applications_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."organisation_applications" validate constraint "organisation_applications_auth_id_fkey";

alter table "public"."organisation_applications" add constraint "organisation_applications_auth_id_tenant_id_key" UNIQUE using index "organisation_applications_auth_id_tenant_id_key";

grant delete on table "public"."organisation_applications" to "anon";

grant insert on table "public"."organisation_applications" to "anon";

grant references on table "public"."organisation_applications" to "anon";

grant select on table "public"."organisation_applications" to "anon";

grant trigger on table "public"."organisation_applications" to "anon";

grant truncate on table "public"."organisation_applications" to "anon";

grant update on table "public"."organisation_applications" to "anon";

grant delete on table "public"."organisation_applications" to "authenticated";

grant insert on table "public"."organisation_applications" to "authenticated";

grant references on table "public"."organisation_applications" to "authenticated";

grant select on table "public"."organisation_applications" to "authenticated";

grant trigger on table "public"."organisation_applications" to "authenticated";

grant truncate on table "public"."organisation_applications" to "authenticated";

grant update on table "public"."organisation_applications" to "authenticated";

grant delete on table "public"."organisation_applications" to "service_role";

grant insert on table "public"."organisation_applications" to "service_role";

grant references on table "public"."organisation_applications" to "service_role";

grant select on table "public"."organisation_applications" to "service_role";

grant trigger on table "public"."organisation_applications" to "service_role";

grant truncate on table "public"."organisation_applications" to "service_role";

grant update on table "public"."organisation_applications" to "service_role";

create policy "tenant_isolation"
on "public"."organisation_applications"
as permissive
for all
to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));
