create table "public"."organisation_signup_settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "description" text not null,
    "image_url" text,
    "tenant_id" text not null
);

alter table "public"."organisation_signup_settings" enable row level security;

CREATE UNIQUE INDEX organisation_signup_settings_pkey ON public.organisation_signup_settings USING btree (id);

CREATE UNIQUE INDEX organisation_signup_settings_tenant_id_key ON public.organisation_signup_settings USING btree (tenant_id);

alter table "public"."organisation_signup_settings" add constraint "organisation_signup_settings_pkey" PRIMARY KEY using index "organisation_signup_settings_pkey";

alter table "public"."organisation_signup_settings" add constraint "organisation_signup_settings_tenant_id_key" UNIQUE using index "organisation_signup_settings_tenant_id_key";

grant delete on table "public"."organisation_signup_settings" to "anon";

grant insert on table "public"."organisation_signup_settings" to "anon";

grant references on table "public"."organisation_signup_settings" to "anon";

grant select on table "public"."organisation_signup_settings" to "anon";

grant trigger on table "public"."organisation_signup_settings" to "anon";

grant truncate on table "public"."organisation_signup_settings" to "anon";

grant update on table "public"."organisation_signup_settings" to "anon";

grant delete on table "public"."organisation_signup_settings" to "authenticated";

grant insert on table "public"."organisation_signup_settings" to "authenticated";

grant references on table "public"."organisation_signup_settings" to "authenticated";

grant select on table "public"."organisation_signup_settings" to "authenticated";

grant trigger on table "public"."organisation_signup_settings" to "authenticated";

grant truncate on table "public"."organisation_signup_settings" to "authenticated";

grant update on table "public"."organisation_signup_settings" to "authenticated";

grant delete on table "public"."organisation_signup_settings" to "service_role";

grant insert on table "public"."organisation_signup_settings" to "service_role";

grant references on table "public"."organisation_signup_settings" to "service_role";

grant select on table "public"."organisation_signup_settings" to "service_role";

grant trigger on table "public"."organisation_signup_settings" to "service_role";

grant truncate on table "public"."organisation_signup_settings" to "service_role";

grant update on table "public"."organisation_signup_settings" to "service_role";

create policy "tenant_isolation"
on "public"."organisation_signup_settings"
as permissive
for all
to public
using ((tenant_id = ((( SELECT current_setting('request.headers'::text, true) AS current_setting))::json ->> 'x-tenant-id'::text)));
