create table "public"."email_content_reach" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone,
    "tenant_id" text,
    "name" text,
    "preferences_label" text,
    "create_content_label" text,
    "default_option" boolean not null default false
);


alter table "public"."email_content_reach" enable row level security;

alter table "public"."news" add column "email_content_reach" bigint;

alter table "public"."notifications_preferences" add column "email_content_reach" bigint;

CREATE UNIQUE INDEX email_content_reach_pkey ON public.email_content_reach USING btree (id);

alter table "public"."email_content_reach" add constraint "email_content_reach_pkey" PRIMARY KEY using index "email_content_reach_pkey";

alter table "public"."news" add constraint "news_email_content_reach_fkey" FOREIGN KEY (email_content_reach) REFERENCES email_content_reach(id) not valid;

alter table "public"."news" validate constraint "news_email_content_reach_fkey";

alter table "public"."notifications_preferences" add constraint "notifications_preferences_email_content_reach_fkey" FOREIGN KEY (email_content_reach) REFERENCES email_content_reach(id) not valid;

alter table "public"."notifications_preferences" validate constraint "notifications_preferences_email_content_reach_fkey";

grant delete on table "public"."email_content_reach" to "anon";

grant insert on table "public"."email_content_reach" to "anon";

grant references on table "public"."email_content_reach" to "anon";

grant select on table "public"."email_content_reach" to "anon";

grant trigger on table "public"."email_content_reach" to "anon";

grant truncate on table "public"."email_content_reach" to "anon";

grant update on table "public"."email_content_reach" to "anon";

grant delete on table "public"."email_content_reach" to "authenticated";

grant insert on table "public"."email_content_reach" to "authenticated";

grant references on table "public"."email_content_reach" to "authenticated";

grant select on table "public"."email_content_reach" to "authenticated";

grant trigger on table "public"."email_content_reach" to "authenticated";

grant truncate on table "public"."email_content_reach" to "authenticated";

grant update on table "public"."email_content_reach" to "authenticated";

grant delete on table "public"."email_content_reach" to "service_role";

grant insert on table "public"."email_content_reach" to "service_role";

grant references on table "public"."email_content_reach" to "service_role";

grant select on table "public"."email_content_reach" to "service_role";

grant trigger on table "public"."email_content_reach" to "service_role";

grant truncate on table "public"."email_content_reach" to "service_role";

grant update on table "public"."email_content_reach" to "service_role";

create policy "tenant_isolation"
on "public"."email_content_reach"
as permissive
for all
to public
using ((tenant_id = ((current_setting('request.headers'::text, true))::json ->> 'x-tenant-id'::text)));



