create table "public"."remakes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "modified_at" timestamp with time zone,
    "project_id" bigint not null,
    "created_by" bigint not null,
    "description" text,
    "images" json not null,
    "tenant_id" text not null
);

alter table "public"."remakes" enable row level security;

CREATE UNIQUE INDEX remakes_pkey ON public.remakes USING btree (id);

alter table "public"."remakes" add constraint "remakes_pkey" PRIMARY KEY using index "remakes_pkey";

alter table "public"."remakes" add constraint "remakes_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."remakes" validate constraint "remakes_project_id_fkey";

alter table "public"."remakes" add constraint "remakes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."remakes" validate constraint "remakes_created_by_fkey";

CREATE INDEX remakes_project_id_created_at_idx ON public.remakes USING btree (project_id, created_at DESC);

create policy "tenant_isolation" on "public"."remakes" as permissive for all to public using ((tenant_id = ((SELECT current_setting('request.headers', true))::json ->> 'x-tenant-id')));

grant delete on table "public"."remakes" to "anon";

grant insert on table "public"."remakes" to "anon";

grant references on table "public"."remakes" to "anon";

grant select on table "public"."remakes" to "anon";

grant trigger on table "public"."remakes" to "anon";

grant truncate on table "public"."remakes" to "anon";

grant update on table "public"."remakes" to "anon";

grant delete on table "public"."remakes" to "authenticated";

grant insert on table "public"."remakes" to "authenticated";

grant references on table "public"."remakes" to "authenticated";

grant select on table "public"."remakes" to "authenticated";

grant trigger on table "public"."remakes" to "authenticated";

grant truncate on table "public"."remakes" to "authenticated";

grant update on table "public"."remakes" to "authenticated";

grant references on table "public"."remakes" to "service_role";

grant trigger on table "public"."remakes" to "service_role";

grant truncate on table "public"."remakes" to "service_role";
