name: Deploy Fly PR Preview
on:
  pull_request_target:
    types: [labeled, synchronize]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: ams
  FLY_ORG: one-army
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.PREVIEW_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ secrets.PREVIEW_PROJECT_ID }}
  FLY_APP_NAME: community-platform-pr-${{ github.event.number }}

jobs:
  preview_app:
    if: contains(github.event.pull_request.labels.*.name, 'Review allow-preview ✅')
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}-${{ github.sha }}

    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> "$GITHUB_PATH"

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.5.0
        with:
          config: fly-preview.toml
          name: community-platform-pr-${{ github.event.number }}
          args: --build-arg COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          secrets: |
            SUPABASE_API_URL=${{ secrets.SUPABASE_API_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
